---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minijs
  labels:
    app: minijs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minijs
  template:
    metadata:
      labels:
        app: minijs
    spec:
      containers:
      - name: minijs
        image: localhost:5000/minijs
        imagePullPolicy: IfNotPresent
        env:
        - name: SOME_ENV
          value: $SOME_ENV
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: myjob
        #       key: DB_HOST
        # ports:
        # - containerPort: 80
        #   name: myjob
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Europe/Warsaw
      restartPolicy: Always
